name: screenwriter
services:
- name: web
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/screenwriter
  build_command: pip install -r requirements.txt
  run_command: streamlit run main.py --server.port=$PORT --server.address=0.0.0.0
  instance_count: 2
  instance_size_slug: basic-xxs
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: PYTHON_VERSION
    scope: RUN_TIME
    value: "3.9"
  routes:
  - path: /
  health_check:
    http_path: /_stcore/health
    initial_delay_seconds: 10
    period_seconds: 10

alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED 